// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 17.06.2026, 15:44:45
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/vladimir/www/api/frontend/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/vladimir/www/api/frontend/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/vladimir/www/api/frontend/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/vladimir/www/api/frontend/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/vladimir/www/api/frontend/app/plugins/**/*.{js,ts,mjs}","/home/vladimir/www/api/frontend/app/composables/**/*.{js,ts,mjs}","/home/vladimir/www/api/frontend/app/utils/**/*.{js,ts,mjs}","/home/vladimir/www/api/frontend/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/vladimir/www/api/frontend/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/vladimir/www/api/frontend/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/vladimir/www/api/frontend/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;