// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 13.06.2026, 14:54:29
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/проекты/Practical/frontend/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/проекты/Practical/frontend/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/проекты/Practical/frontend/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/проекты/Practical/frontend/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/проекты/Practical/frontend/app/plugins/**/*.{js,ts,mjs}","C:/проекты/Practical/frontend/app/composables/**/*.{js,ts,mjs}","C:/проекты/Practical/frontend/app/utils/**/*.{js,ts,mjs}","C:/проекты/Practical/frontend/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/проекты/Practical/frontend/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/проекты/Practical/frontend/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/проекты/Practical/frontend/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;