// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/categories/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories/[id].get').default>>>>
    }
    '/api/cities/suggestions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cities/suggestions.get').default>>>>
    }
    '/api/products/suggestionsProducts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/suggestionsProducts.get').default>>>>
    }
    '/api/products/suggestionsPromt': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/suggestionsPromt.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/_i18n/:hash/:locale/messages.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxtjs/i18n/dist/runtime/server/routes/messages').default>>>>
    }
  }
}
export {}